version: '3'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: my_pass
      POSTGRES_DB: go_rest
    ports:
      - '54320:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - db

volumes:
  postgres-data:
